version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: node dist/server.js
    restart: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "8081:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: node-ts-boiler
      MYSQL_ROOT_PASSWORD: $DB_PASS

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
